# Data preprocessing parameters
preprocess:
  sample_rate: 16000
  duration: 4  # seconds
  max_audio_length: 64000  # 4 seconds at 16kHz
  normalize: true

# Feature extraction parameters
features:
  mfcc:
    n_mfcc: 40
    n_fft: 2048
    hop_length: 512
    n_mels: 128
    fmin: 0
    fmax: 8000
    
  spectrogram:
    n_fft: 2048
    hop_length: 512
    n_mels: 128
    fmin: 0
    fmax: 8000
    
  delta:
    order: 2  # Include delta and delta-delta features

# Model parameters
models:
  random_forest:
    n_estimators: 200
    max_depth: 20
    min_samples_split: 5
    min_samples_leaf: 2
    max_features: 'sqrt'
    random_state: 42
    n_jobs: -1
    
  cnn:
    epochs: 50
    batch_size: 32
    learning_rate: 0.001
    dropout: 0.5
    early_stopping_patience: 5
    reduce_lr_patience: 3
    
  ensemble:
    method: 'voting'  # 'voting' or 'stacking'
    weights: [0.5, 0.5]  # [RF, CNN]

# Training parameters
training:
  random_seed: 42
  use_class_weights: true

# Evaluation parameters
evaluation:
  metrics:
    - accuracy
    - precision
    - recall
    - f1_score
    - eer
    - auc_roc
